### ISSUE TITLE
Gateway authentication failure

### ISSUE THREAD

**Issue by BitpixAgency** [tiipiik/SmsSender#9]
Hi,

We are using Clickatell as our sms provider.

We are getting an `Gateway authentication failure` error as reported by the dashboard widget.

Does this plugin support Clickatell sandbox environments or just production?

Which Clickatell API is it using? Basic HTTP or One?

**Comment by tiipiik** [comment]
Hi,
Sorry but I actually have no time to make support for this plugin. As it would work "as is", it is not updated anymore (I will add message to front), and I think that due to plateforms (Clickatell & Twilio), updates, this plugin is probably not compatible anymore.
Anyway, I would be happy to add code if someone makes a PR.
